# generated by datamodel-codegen:
#   filename:  aggiornamento_odonimi.yml
#   timestamp: 2026-01-20T15:44:48+00:00

from __future__ import annotations

from enum import Enum
from typing import Annotated

from pydantic import AnyUrl, BaseModel, Extra, Field, StringConstraints, model_validator


class TipoOperazione(Enum):
    I = 'I'
    R = 'R'
    S = 'S'


class Provvedimento(BaseModel):
    data: str | None = Field(
        None, description='Data del provvedimento', example='10/10/2023'
    )
    protocollo: Annotated[str, StringConstraints(max_length=70)] | None = Field(
        None,
        description="Protocollo del provvedimento. Non viene applicato l'uppercase",
        example='1234567/abc',
    )
    flag_delibera: Annotated[int, Field(ge=0, le=4)] | None = Field(
        None,
        description='Flag della delibera (valori numerici da 0 a 4). I valori 0 e 1 rendono obbligatorie le informazioni data e protocollo',
        example='1',
    )

    @model_validator(mode='after')
    def validate_provvedimento_fields(self):
        if self.flag_delibera in [0, 1]:
            if not self.data or not self.protocollo:
                raise ValueError('data e protocollo sono obbligatori quando flag_delibera è 0 o 1')
        return self


class AutPrefettura(BaseModel):
    data_pref: str | None = Field(
        None,
        description='Data della prefettura. Obbligatoria se è presente il protocollo_pref',
        example='10/10/2023',
    )
    protocollo_pref: Annotated[str, StringConstraints(max_length=70)] | None = Field(
        None,
        description="Protocollo della prefettura. Non viene applicato l'uppercase. Obbligatorio se è presente data_pref",
        example='Prot.Gen.1234567',
    )

    @model_validator(mode='after')
    def validate_protocollo_pref(self):
        if self.data_pref and not self.protocollo_pref:
            raise ValueError('protocollo_pref è obbligatorio quando data_pref è presente')
        return self

    


class Richiesta(BaseModel):
    codcom: str = Field(
        ..., description='Codice del comune (obbligatorio)', example='A062'
    )
    tipo_operazione: TipoOperazione | None = Field(
        None,
        description="Tipo di operazione ('S'=Soppressione, 'I'=Inserimento, 'R'=Aggiornamento)",
        example='R',
    )
    progr_nazionale: Annotated[str, StringConstraints(max_length=10)] | None = Field(
        None,
        description='Progressivo nazionale (obbligatorio per soppressione e aggiornamento)',
        example='2000449',
    )

    @model_validator(mode='after')
    def validate_progr_nazionale(self):
        if self.tipo_operazione in [TipoOperazione.S, TipoOperazione.R]:
            if not self.progr_nazionale:
                raise ValueError('progr_nazionale è obbligatorio quando tipo_operazione è S o R')
        return self
    
    codice_comunale: Annotated[str, StringConstraints(max_length=30)] | None = Field(
        None,
        description="Codifica comunale dell'odonimo. Non viene applicato l'uppercase",
        example='75439 d',
    )
    dug: Annotated[str, StringConstraints(max_length=30)] | None = Field(
        None,
        description='DUG (obbligatorio per inserimento e aggiornamento, non ammesso per soppressione, non soggetto a controllo di esistenza nel dizionario)',
        example='VIA',
    )

    @model_validator(mode='after')
    def validate_dug(self):
        if self.tipo_operazione in [TipoOperazione.I, TipoOperazione.R]:
            if not self.dug:
                raise ValueError('dug è obbligatorio quando tipo_operazione è I o R')
        if self.tipo_operazione == TipoOperazione.S:
            if self.dug:
                raise ValueError('dug non è ammesso quando tipo_operazione è S')
        return self
    
    denom_delibera: Annotated[str, StringConstraints(max_length=120)] | None = Field(
        None,
        description="Denominazione Delibera. Viene applicato l'uppercase",
        example='DELLE ORCHIDEE',
    )
    denom_in_lingua_1: Annotated[str, StringConstraints(max_length=150)] | None = Field(
        None,
        description="Odonimo in lingua, comprensivo della dug, per comuni bi/tri lingue. Viene applicato l'uppercase",
        example='ODONIMO LINGUA 1',
    )
    denom_in_lingua_2: Annotated[str, StringConstraints(max_length=150)] | None = Field(
        None,
        description="Odonimo in ulteriore lingua, comprensivo della dug, per comuni tri lingue. Viene applicato l'uppercase",
        example='ODONIMO LINGUA 2',
    )
    denom_localita: Annotated[str, StringConstraints(max_length=151)] | None = Field(
        None,
        description="Denominazione Località. Viene applicato l'uppercase",
        example='CASAL PALOCCO',
    )
    provvedimento: Provvedimento | None = None
    aut_prefettura: AutPrefettura | None = None
    data_valid_amm: str | None = Field(
        None,
        description='Data di validità amministrativa, minore o uguale della data corrente per inserimento e soppressione. Per aggiornamento anche >= della precedente',
        example='08/10/2024',
    )


class RichiestaOperazione(BaseModel):
    richiesta: Richiesta | None = None
