# generated by datamodel-codegen:
#   filename:  aggiornamento_interni.yml
#   timestamp: 2026-01-19T16:27:59+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class RichiestaOperazione(BaseModel):
    codcom: str | None = Field(None, description='Codice del comune')
    progr_civico: str | None = Field(None, description='Progressivo accesso')
    progr_interno: str | None = Field(None, description='Progressivo interno')
    interno: str | None = Field(None, description='Interno')
    tipo_operazione: str | None = Field(None, description='Tipo di operazione')
    codice_interno_comunale: str | None = Field(
        None, description='Codice interno comunale'
    )
    cortile: str | None = Field(None, description='Cortile')
    edificio: str | None = Field(None, description='Edificio')
    scala: str | None = Field(None, description='Scala')
    piano: str | None = Field(None, description='Piano')
    esponente_interno: str | None = Field(None, description='Esponente interno')


class DatiItem(BaseModel):
    progr_nazionale_ni: str | None = Field(None, description='Progressivo nazionale NI')
    progr_nazionale_nc: str | None = Field(None, description='Progressivo nazionale NC')
    codice_comunale_ni: str | None = Field(None, description='Codice comunale NI')
    interno: str | None = Field(None, description='Interno')
    cortile: str | None = Field(None, description='Cortile')
    edificio: str | None = Field(None, description='Edificio')
    scala: str | None = Field(None, description='Scala')
    piano: str | None = Field(None, description='Piano')
    data_inizio_ni: str | None = Field(None, description='Data di inizio NI')
    data_fine_ni: str | None = Field(None, description='Data di fine NI')
    data_aggiornamento_ni: str | None = Field(
        None, description='Data di aggiornamento NI'
    )
    esponente_interno: str | None = Field(None, description='Esponente interno')


class RispostaOperazione(BaseModel):
    idRichiesta: constr(max_length=15) | None = Field(
        None, description='Identificativo assegnato alla richiesta', example='5144'
    )
    esito: str | None = Field(None, description="Esito dell'operazione", example='0')
    messaggio: str | None = Field(
        None, description="Messaggio associato all'esito", example='OK'
    )
    dati: list[DatiItem] | None = None


class RispostaErrore(BaseModel):
    id: str | None = Field(
        None, description="Identificativo dell'operazione.", example='5144'
    )
    codice: str | None = Field(None, description='Codice di errore', example='23')
    messaggio: str | None = Field(
        None,
        description='Messaggio di errore.',
        example='Errore di validazione: [specifica qui il messaggio di errore]',
    )
