# generated by datamodel-codegen:
#   filename:  SpecificaAPI.yaml
#   timestamp: 2025-12-22T15:33:39+00:00

from typing import Annotated
from pydantic import ( 
    BaseModel,
    Field, 
    StringConstraints, 
    model_validator
)

from .coordinate import Coordinate
from .mtype import TipoOperazione


class AccessoAggiornamentiAccessi(BaseModel):
    progr_civico: Annotated[str, StringConstraints(max_length=15)] | None = Field(
        None,
        description="Progressivo accesso (obbligatorio solo per operazione_civico='R','S')",
        example='1370588',
    )
    
    @model_validator(mode='after')
    def check_progr_civico_required(self):
        if self.operazione_civico in [TipoOperazione.R, TipoOperazione.S] and not self.progr_civico:
            raise ValueError("progr_civico è obbligatorio quando operazione_civico è 'R' o 'S'")
        return self
    
    codice_civico_comunale: Annotated[str, StringConstraints(max_length=30)] | None = Field(
        None, description="Codifica comunale dell'accesso", example='7569A'
    )

    numero: Annotated[str, StringConstraints(max_length=5)] | None = Field(
        None,
        description="Numero civico, da non valorizzare per operazione_civico='S' o accesso identificato con il sistema metrico",
        example='12',
    )
    
    @model_validator(mode='after')
    def check_numero_constraints(self):
        if self.operazione_civico == TipoOperazione.S and self.numero:
            raise ValueError("numero non deve essere valorizzato quando operazione_civico è 'S'")
        if self.metrico and self.numero:
            raise ValueError("numero non deve essere valorizzato quando l'accesso è identificato con il sistema metrico")
        return self


    esponente: Annotated[str, StringConstraints(max_length=15)] | None = Field(
        None,
        description="Da valorizzare se necessario per identificare l'accesso, solo per tipo_operazione='I','R'",
        example='A',
    )
    specificita: Annotated[str, StringConstraints(max_length=5)] | None = Field(
        None,
        description="da valorizzare se necessario per identificare l'accesso per comuni specifici, solo per tipo_operazione='I','R'",
        example='ROSSO',
    )
    metrico: Annotated[str, StringConstraints(max_length=6)] | None = Field(
        None,
        description="metrico, da non valorizzare per operazione_civico='S' o accesso identificato con il numero civico",
        example='300',
    )
    
    @model_validator(mode='after')
    def check_metrico_constraints(self):
        if self.operazione_civico == TipoOperazione.S and self.metrico:
            raise ValueError("metrico non deve essere valorizzato quando operazione_civico è 'S'")
        if self.numero and self.metrico:
            raise ValueError("metrico non deve essere valorizzato quando l'accesso è identificato con il numero civico")
        return self
    
    sezione_censimento: Annotated[str, StringConstraints(max_length=13)] | None = Field(
        None,
        description="Sezione di censimento, da valorizzare solo per operazione_civico='I','R'",
        example='9',
    )
    
    @model_validator(mode='after')
    def check_sezione_censimento_operation(self):
        if self.sezione_censimento and self.operazione_civico not in [TipoOperazione.I, TipoOperazione.R]:
            raise ValueError("sezione_censimento può essere valorizzato solo quando operazione_civico è 'I' o 'R'")
        return self
    
    operazione_civico: TipoOperazione | None = Field(
        None,
        description="Tipo di operazione sull'accesso. 'I'=inserimento, 'R'=aggiornamento, 'S'=soppressione",
        example='R',
    )

    coordinate: Coordinate | None = None
    
    data_valid_amm: str | None = Field(
        None,
        description="Data di validita' amministrativa, se assente è equiparata alla data corrente, per tipo_operazione=S rappresenta la data di fine validita per le altre operazioni la data di inizio",
        example='08/10/2024',
    )
    isolato: Annotated[str, StringConstraints(max_length=4)] | None = Field(
        None,
        description="Codice isolato, facoltativo, da valorizzare solo per operazione_civico='I','R'",
        example='101',
    )
    
    @model_validator(mode='after')
    def check_isolato_operation(self):
        if self.isolato and self.operazione_civico not in [TipoOperazione.I, TipoOperazione.R]:
            raise ValueError("isolato può essere valorizzato solo quando operazione_civico è 'I' o 'R'")
        return self


class RichiestaAggiornamentoAccessi(BaseModel):
    codcom: str | None = Field(
        None, description='Codice del comune (obbligatorio)', example='A062'
    )
    progr_nazionale: Annotated[str, StringConstraints(max_length=10)] | None = Field(
        None, description='Progressivo nazionale (obbligatorio)', example='2000449'
    )
    accesso: AccessoAggiornamentiAccessi | None = None



