# generated by datamodel-codegen:
#   filename:  consultazione_comuni.yml
#   timestamp: 2026-02-19T13:19:10+00:00

from __future__ import annotations

from pydantic import AnyUrl, BaseModel, Extra, Field, conint, constr


class Problem(BaseModel):
    class Config:
        extra = Extra.forbid

    detail: constr(regex=r'^.{0,1024}$', max_length=4096) | None = Field(
        None,
        description='A human readable explanation specific to this occurrence of the\nproblem. You MUST NOT expose internal informations, personal\ndata or implementation details through this field.\n\n`detail` supports localized patterns whereas `title` pattern is only in ascii.\n',
        example='Request took too long to complete.',
    )
    instance: AnyUrl | None = Field(
        None,
        description='An absolute URI that identifies the specific occurrence of the problem.\nIt may or may not yield further information if dereferenced.\n',
    )
    status: conint(ge=100, lt=600) | None = Field(
        None,
        description='The HTTP status code generated by the origin server for this occurrence\nof the problem.\n',
        example=503,
    )
    title: constr(regex=r'^[ -~]{0,64}$', max_length=64) | None = Field(
        None,
        description='A short, summary of the problem type. Written in english and readable\nfor engineers (usually not suited for non technical stakeholders and\nnot localized): the expressed pattern does not support unicode characters.\n',
        example='Service Unavailable',
    )
    type: AnyUrl | None = Field(
        'about:blank',
        description='An absolute URI that identifies the problem type.  When dereferenced,\nit SHOULD provide human-readable documentation for the problem type\n(e.g., using HTML).\n',
        example='https://tools.ietf.org/html/rfc7231#section-6.6.4',
    )
