# Generated by Django 3.2.25 on 2024-07-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='QPDNDProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qpdnd_projects', to='qdjango.project')),
            ],
            options={
                'verbose_name': 'PDND Project',
            },
        ),
        migrations.CreateModel(
            name='QPDNDLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('layer', models.ForeignKey(help_text='Select vector project layer to expose for PDND: only follow geometry types are allowed: Point, MultiPoint, Point25D, MultiPointZ, PointZ, Polygon, MultiPolygon, Polygon25D, PolygonZ, MultiPolygonZ, LineString, MultiLineString, LineString25D, LineStringZ, MultiLineStringZ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qpdnd_layer', to='qdjango.layer')),
                ('qpdnd_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qpdnd_layer', to='qpdnd.qpdndproject')),
            ],
            options={
                'verbose_name': 'PDND Layer',
            },
        ),
    ]
