# Generated by Django 3.2.25 on 2024-07-25 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpdndlayer',
            name='endpoint',
            field=models.CharField(default='', help_text='Select API endpoint for PDND layer. must be unique', max_length=255, unique=True),
        ),
    ]
