# Generated by Django 3.2.25 on 2024-07-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0003_auto_20240725_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpdndproject',
            name='version',
            field=models.CharField(default='1.0.0', help_text='Indicate a version for the API to expose. I.e.: 1.0.0 ', max_length=255, null=True),
        ),
    ]
