# Generated by Django 3.2.25 on 2024-07-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0006_alter_qpdndproject_terms_of_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=400)),
                ('spdx_id', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='qpdndproject',
            name='contact_author',
            field=models.CharField(help_text='Author of the service', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='qpdndproject',
            name='contact_email',
            field=models.EmailField(help_text='Email reference', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='qpdndproject',
            name='contact_url',
            field=models.URLField(blank=True, help_text='Contact URL reference', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='qpdndproject',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the project', null=True),
        ),
        migrations.AddField(
            model_name='qpdndproject',
            name='title',
            field=models.CharField(help_text='Title of the service', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='qpdndproject',
            name='x_summary',
            field=models.CharField(help_text='Used to specify a brief, one-liner description of your API: this is very useful for catalog purposes (eg. this can be shown as your API subtitle in catalogs and developer portals)', max_length=400, null=True),
        ),
    ]
