# Generated by Django 3.2.25 on 2024-07-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0007_auto_20240730_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='node_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
