# Generated by Django 3.2.25 on 2024-09-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0010_qpdndproject_x_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpdndproject',
            name='qpdnd_audience',
            field=models.CharField(help_text="PDND Audience of the service, i.e. 'test_cartografico'", max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='qpdndproject',
            name='qpdnd_env',
            field=models.CharField(choices=[('prod', 'PRODUCTION'), ('test', 'TESTING')], help_text='Set the PDND environment for this API (Production, Testing)', max_length=4, null=True),
        ),
    ]
