# Generated by Django 3.2.25 on 2024-09-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0012_alter_qpdndproject_qpdnd_env'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpdndproject',
            old_name='qpdnd_audience',
            new_name='pdnd_audience',
        ),
        migrations.RenameField(
            model_name='qpdndproject',
            old_name='qpdnd_env',
            new_name='pdnd_env',
        ),
    ]
