# Generated by Django 3.2.25 on 2024-10-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0013_auto_20240920_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpdndproject',
            name='pdnd_eservice_is',
            field=models.CharField(help_text='PDND Eservice ID of the service', max_length=600, null=True),
        ),
    ]
