# Generated by Django 3.2.25 on 2024-10-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0014_qpdndproject_pdnd_eservice_is'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qpdndproject',
            old_name='pdnd_eservice_is',
            new_name='pdnd_eservice_id',
        ),
    ]
