# Generated by Django 3.2.25 on 2024-10-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0015_rename_pdnd_eservice_is_qpdndproject_pdnd_eservice_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpdndproject',
            name='terms_of_service',
            field=models.URLField(blank=True, help_text='Set an url where to find the terms fo service. I.e.: https://smartbear.com/terms-of-use/. It is required by Italian Guidelines Extended.', max_length=255, null=True),
        ),
    ]
