# Generated by Django 3.2.25 on 2025-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0016_alter_qpdndproject_terms_of_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='QPDNDClientSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('pdnd_env', models.CharField(choices=[('prod', 'PRODUCTION'), ('test', 'TESTING')], default='test', help_text='Set the PDND environment for this API (Production, Testing)', max_length=4, null=True)),
                ('pdnd_server_kid', models.CharField(help_text='PDND Server KID of the service', max_length=600, null=True)),
                ('pdnd_issuer', models.CharField(help_text='PDND Client Issuer of the service', max_length=600, null=True)),
                ('pdnd_server_issuer', models.CharField(help_text='PDND Server Issuer of the service', max_length=600, null=True)),
                ('pdnd_server_subject', models.CharField(help_text='PDND Server Subject of the service', max_length=600, null=True)),
                ('pdnd_well_known_url', models.URLField(help_text="PDND 'Well Known URL' of the service", max_length=1200, null=True)),
                ('pdnd_api_purpose_verification_url', models.URLField(help_text='PDND API Purpose Verification URL', max_length=1200, null=True)),
                ('pdnd_api_token_url', models.URLField(help_text='PDND API Token URL', max_length=1200, null=True)),
                ('pdnd_audience', models.CharField(help_text="PDND Audience of the service, i.e. 'test_cartografico'", max_length=600, null=True)),
                ('pdnd_eservice_id', models.CharField(help_text='PDND Eservice ID of the service', max_length=600, null=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
            options={
                'verbose_name': 'PDND Client Setting',
            },
        ),
        migrations.RemoveField(
            model_name='qpdndproject',
            name='pdnd_env',
        )
    ]
