# Generated by Django 3.2.25 on 2025-01-07 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0017_auto_20250107_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpdndproject',
            name='client_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qpdnd.qpdndclientsetting'),
        ),
    ]
