# Generated by Django 3.2.25 on 2025-01-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0018_qpdndproject_client_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qpdndclientsetting',
            name='pdnd_audience',
        ),
        migrations.RemoveField(
            model_name='qpdndclientsetting',
            name='pdnd_eservice_id',
        ),
        migrations.AddField(
            model_name='qpdndclientsetting',
            name='pdnd_private_key',
            field=models.TextField(help_text='You private key in PEM format', null=True),
        ),
        migrations.AlterField(
            model_name='qpdndclientsetting',
            name='pdnd_api_purpose_verification_url',
            field=models.URLField(help_text='PDND API Purpose Verification URL: i.e. <i>https://api.uat.interop.pagopa.it/1.0/purposes/{purposeId}/agreement</i>', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='qpdndclientsetting',
            name='pdnd_api_token_url',
            field=models.URLField(help_text='PDND API Token URL: i.e. <i>https://auth.uat.interop.pagopa.it/token.oauth2</i>', max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='qpdndclientsetting',
            name='pdnd_issuer',
            field=models.CharField(help_text='PDND Client Issuer of the service: i.e. <i>uat.interop.pagopa.it</i>', max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='qpdndclientsetting',
            name='pdnd_well_known_url',
            field=models.URLField(help_text="PDND 'Well Known URL' of the service: i.e. <i>https://uat.interop.pagopa.it/.well-known/jwks.json</i>", max_length=1200, null=True),
        ),
    ]
