# Generated by Django 3.2.25 on 2025-01-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0019_auto_20250108_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='qpdndclientsetting',
            name='pdnd_audience',
            field=models.CharField(help_text='PDND Audience of the service: i.e. auth.uat.interop.pagopa.it/client-assertion', max_length=600, null=True),
        ),
    ]
