# Generated by Django 4.2.22 on 2025-10-10 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0020_qpdndclientsetting_pdnd_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qpdndproject',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_projects', to='qdjango.project'),
        ),
        migrations.CreateModel(
            name='ANNCSUroject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Optional note for the configuration.', null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_anncsu_layers_related', to='qdjango.layer')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_anncsu_projects', to='qdjango.project')),
            ],
        ),
    ]
