# Generated by Django 4.2.22 on 2025-10-10 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0021_alter_qpdndproject_project_anncsuroject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ANNCSUroject',
            new_name='ANNCSUProject',
        ),
    ]
