# Generated by Django 4.2.22 on 2025-10-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0022_rename_anncsuroject_anncsuproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='anncsuproject',
            name='client_setting',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qpdnd.qpdndclientsetting'),
        ),
    ]
