# Generated by Django 4.2.22 on 2025-11-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0023_anncsuproject_client_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anncsuproject',
            name='client_setting',
        ),
        migrations.AddField(
            model_name='anncsuproject',
            name='env_type',
            field=models.CharField(choices=[('prod', 'PRODUCTION'), ('test', 'TESTING')], default='test', max_length=10),
        ),
        migrations.AddField(
            model_name='anncsuproject',
            name='govway_api_endpoint',
            field=models.URLField(help_text='GovWay API endpoint URL', null=True),
        ),
    ]
