# Generated by Django 4.2.22 on 2025-11-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0024_remove_anncsuproject_client_setting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IstatCodiciUi',
            fields=[
                ('codice_regione', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_citta_metropolitana', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_provincia_1', models.CharField(blank=True, max_length=255, null=True)),
                ('progressivo_del_comune_2', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_comune_formato_alfanumerico', models.CharField(blank=True, max_length=255, null=True)),
                ('denominazione_in_italiano', models.CharField(blank=True, max_length=255, null=True)),
                ('denominazione_in_tedesco', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_ripartizione_geografica', models.CharField(blank=True, max_length=255, null=True)),
                ('ripartizione_geografica', models.CharField(blank=True, max_length=255, null=True)),
                ('denominazione_regione', models.CharField(blank=True, max_length=255, null=True)),
                ('denominazione_citta_metropolitana', models.CharField(blank=True, max_length=255, null=True)),
                ('denominazione_provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('flag_comune_capoluogo_di_provincia', models.CharField(blank=True, max_length=255, null=True)),
                ('sigla_automobilistica', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_comune_formato_numerico', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('codice_comune_numerico_con_107_province_dal_2006_al_2009', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_comune_numerico_con_103_province_dal_1995_al_2005', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_catastale_del_comune', models.CharField(blank=True, max_length=255, null=True)),
                ('popolazione_legale_2011_09_10_2011', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_nuts1_2010', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_nuts2_2010_3', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_nuts3_2010', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_nuts1_2006', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_nuts2_2006_3', models.CharField(blank=True, max_length=255, null=True)),
                ('codice_nuts3_2006', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'ISTAT Codici UI',
                'verbose_name_plural': 'ISTAT Codici UI',
            },
        ),
    ]
