# Generated by Django 4.2.22 on 2025-11-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0025_istatcodiciui'),
    ]

    operations = [
        migrations.AddField(
            model_name='anncsuproject',
            name='codice_comune',
            field=models.ForeignKey(help_text='Municipality code (ISTAT code).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='qpdnd.istatcodiciui'),
        ),
    ]
