# Generated by Django 4.2.22 on 2025-11-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0026_anncsuproject_codice_comune'),
    ]

    operations = [
        migrations.AddField(
            model_name='anncsuproject',
            name='task_id',
            field=models.CharField(blank=True, help_text='Asynchronous task ID.', max_length=255, null=True),
        ),
    ]
