# Generated by Django 4.2.22 on 2025-12-09 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0027_anncsuproject_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anncsuproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_anncsu_projects', to='qdjango.project'),
        ),
    ]
