# Generated by Django 4.2.22 on 2025-12-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0028_alter_anncsuproject_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='anncsuproject',
            name='govway_password',
            field=models.CharField(blank=True, help_text='GovWay API password', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='anncsuproject',
            name='govway_username',
            field=models.CharField(blank=True, help_text='GovWay API username', max_length=255, null=True),
        ),
    ]
