# Generated by Django 4.2.27 on 2026-02-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0029_anncsuproject_govway_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anncsuproject',
            name='api_type',
            field=models.CharField(choices=[('aggcoord', 'AGGIORNAMENTO COORDINATE'), ('aggacc', 'AGGIORNAMENTO ACCESSI')], default='aggcoord', max_length=10),
        ),
    ]
