# Generated by Django 4.2.27 on 2026-02-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0031_anncsuproject_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anncsuproject',
            name='api_type',
            field=models.CharField(choices=[('aggcoord', 'AGGIORNAMENTO COORDINATE'), ('aggacc', 'AGGIORNAMENTO ACCESSI'), ('conscom', 'CONSULTAZIONE COMUNI')], default='aggcoord', max_length=10),
        ),
    ]
