# Generated by Django 4.2.29 on 2026-03-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qpdnd', '0032_alter_anncsuproject_api_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anncsuproject',
            options={'permissions': (('send_to_pdnd', 'Can send features to PDND API'),)},
        ),
    ]
