# Generated by Django 4.2.30 on 2026-05-14 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qpdnd', '0033_alter_anncsuproject_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ANNCSUTaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('send_type', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, help_text='Final result of the task or error message.', null=True)),
                ('anncsu_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to='qpdnd.anncsuproject')),
                ('user', models.ForeignKey(blank=True, help_text='User who started the task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qpdnd_anncsu_task_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ANNCSU Task History',
                'verbose_name_plural': 'ANNCSU Task History',
                'ordering': ('-started_at',),
            },
        ),
    ]
